version: 0.2
phases:  
  pre_build:
    commands:
      - pip --version
      - pip install --upgrade pip
      - pip --version
      - pip install -r requirements.txt
  build:
    commands:
      - export BD_PORT=$BD_PORT
      - export DB_ADDRESS=$DB_ADDRESS
      - export DB_NAME=$DB_NAME
      - export DB_PASSWORD=$DB_PASSWORD
      - export DB_USER=$DB_USER
  post_build:
    commands:
      - python realtime.py
